### ISSUE TITLE
Program crashes when trying to change Games

### ISSUE THREAD

**Issue by scrosner** [smrealms/mgu#2]
```
   at MGU.MainStuff.AddGalaxies() in E:\Code\SMR\mgu\MGU\Forms\MainStuff.cs:line 1332
   at MGU.MainStuff.ChangeGame(Object sender, EventArgs e) in E:\Code\SMR\mgu\MGU\Forms\MainStuff.cs:line 951
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MGU.MainStuff.Main(String[] args) in E:\Code\SMR\mgu\MGU\Forms\MainStuff.cs:line 70
```

**Comment by scrosner** [comment]
Initial findings: index for handling the current/previous game is off by one.

Initial fix stops the crash and game switching works, but looking at the array of "games" there is an Undefined game in the "1" index.

[0] Game 1
[1] Undefined
[2] Game 2
[3] Game 3

Need to trouble shoot how that array is getting set and fix the collection so that it does not skip an index.
